In [2]:
def fib(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    elif n > 2: 
        return(fib(n - 1) + fib (n - 2))
    

In [3]:
print (fib(40))

165580141


In [4]:
print (fib(2))


2


In [5]:
from functools import lru_cache

In [6]:
@lru_cache()
def fib(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    else: 
        return(fib(n - 1) + fib (n - 2))

In [7]:
fib(40)

165580141

In [10]:
class Planet():
    def __init__(self, name, radius):
        self.name = name
        self.radius = radius
    def get_volume(self):
        return self.radius**3 * 3.1415*3/4

mars = Planet ('Mars', 12)
print(f'volume Mars is {mars.get_volume()}')

class GasPlanet (Planet):
    def get_mass(self):
        return self.get_volume()*2
saturn = GasPlanet ('Saturn', 100)
print(f'mass Saturn is {saturn.get_mass()}')
print(f'mass MARS is {mars.get_mass()}')
    

volume Mars is 4071.3840000000005
mass Saturn is 4712250.0


AttributeError: 'Planet' object has no attribute 'get_mass'

In [12]:
import numpy as np

In [28]:
a = np.array([[1,2,34], [23, 48, 19]])

In [29]:
print (a)

[[ 1  2 34]
 [23 48 19]]


In [25]:
np.square(a)

array([[[   1,    4, 1156],
        [ 529, 2304,  361]],

       [[   1,    4, 1156],
        [ 529, 2304,  361]]])

In [26]:
a+a

array([[[ 2,  4, 68],
        [46, 96, 38]],

       [[ 2,  4, 68],
        [46, 96, 38]]])

In [30]:
a.shape

(2, 3)

In [33]:
np.sum(np.square(np.linspace(0, 1000000, 10000000)))

3.3333335000000174e+18

In [34]:
import time
start = time.time()
a = np.sum(np.square(np.linspace(0, 1000000, 10000000)))
print (a)
print(time.time() - start)

3.3333335000000174e+18
0.10366249084472656


In [35]:
%time print(sum ([x**2 for x in range(1000000)]))

333332833333500000
CPU times: user 351 ms, sys: 16 ms, total: 367 ms
Wall time: 367 ms


In [36]:
%time np.sum(np.square(np.linspace(0, 1000000, 10000000)))

CPU times: user 109 ms, sys: 52 ms, total: 161 ms
Wall time: 100 ms


3.3333335000000174e+18

In [ ]:
%